#!/usr/bin/env python3
"""Generate / verify the tpt-physics validation-status table.

This is the automation behind the "Validated vs Experimental" maturity table in
the root README. It scans every crate for `#[ignore]`d tests (known-failing /
slow / experimental capabilities) and:

  1. prints a Markdown table of crates that carry ignored tests (the things that
     MUST stay "Experimental" in the README), and
  2. with ``--check``, fails (exit 1) if the README maturity table marks a crate
     that has ignored tests as "Validated" -- i.e. it stops a capability claim
     from silently drifting out of sync with the test suite.

Usage:
    python3 scripts/gen_status.py            # print the status table
    python3 scripts/gen_status.py --check    # CI gate (exit 1 on drift)
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CRATES_DIR = REPO / "crates"
README = REPO / "README.md"

IGNORE_RE = re.compile(r"^\s*#\[ignore", re.MULTILINE)
# A "Validated" maturity-table row: "| <capability> | ✅ Validated | ..."
VALIDATED_RE = re.compile(r"^\|\s*([^|]+?)\s*\|\s*✅\s*Validated\s*\|", re.IGNORECASE)
# Tokens extracted from an ignored-test filename (e.g. `lid_driven_cavity` ->
# {lid, driven, cavity}) are matched against Validated-row text so only the
# *specific* capability that carries an ignored test is flagged, not every
# Validated row in the same crate.
STOPWORDS = {"test", "tests", "ignored", "mod"}


def tokens(s: str) -> set[str]:
    return {t for t in re.findall(r"[a-z0-9]+", s.lower()) if t not in STOPWORDS}


def crate_has_ignored(crate: Path) -> list[str]:
    """Return the list of files containing a real `#[ignore]` attribute."""
    hits: list[str] = []
    for root, _dirs, files in os.walk(crate):
        for f in files:
            if not f.endswith(".rs"):
                continue
            p = Path(root) / f
            try:
                text = p.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if IGNORE_RE.search(text):
                hits.append(str(p.relative_to(REPO)))
    return hits


def main() -> int:
    check = "--check" in sys.argv[1:]

    crates = sorted(p for p in CRATES_DIR.iterdir() if p.is_dir())
    ignored_by_crate: dict[str, list[str]] = {}
    for c in crates:
        hits = crate_has_ignored(c)
        if hits:
            ignored_by_crate[c.name] = hits

    print("# Validation status (auto-generated by scripts/gen_status.py)\n")
    print("Crates carrying `#[ignore]`d tests are **Experimental** by definition:\n")
    print("| Crate | Ignored-test files |")
    print("| --- | --- |")
    if ignored_by_crate:
        for name, files in ignored_by_crate.items():
            print(f"| `{name}` | {', '.join(files)} |")
    else:
        print("| _(none)_ | _(no ignored tests)_ |")

    drift: list[str] = []
    if README.exists() and check:
        # Capability keywords derived from the ignored-test filenames. A Validated
        # row is drift only if it names one of these specific capabilities.
        ignored_tokens: set[str] = set()
        for files in ignored_by_crate.values():
            for f in files:
                ignored_tokens |= tokens(Path(f).stem)

        readme_text = README.read_text(encoding="utf-8")
        for line in readme_text.splitlines():
            m = VALIDATED_RE.match(line)
            if not m:
                continue
            capability = m.group(1).strip()
            if tokens(capability) & ignored_tokens:
                drift.append(
                    f"README marks '{capability}' as Validated, but an ignored test "
                    f"exists for that capability ({sorted(ignored_tokens & tokens(capability))})"
                )

    if drift:
        print("\n## DRIFT DETECTED\n")
        for d in drift:
            print(f"- {d}")
        print(
            "\nA capability with ignored tests must stay 'Experimental' in the "
            "README maturity table."
        )
        return 1

    if check:
        print("\nOK: no maturity-table drift (Validated capabilities have no ignored tests).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
